USE VUDYOG

IF EXISTS(SELECT [NAME] FROM SYS.PROCEDURES WHERE [NAME]='USP_GET_USERWISE_SETTINGS')
BEGIN
	DROP PROCEDURE USP_GET_USERWISE_SETTINGS
END
GO
CREATE PROCEDURE USP_GET_USERWISE_SETTINGS
@PRODCODE VARCHAR(MAX)
AS
BEGIN
	SELECT DISTINCT A.PRODCODE AS PRODCODE, 'ROLE' AS  CUSERROLES, A.[USER_ROLES] AS CUSRROLENM,
			CAST('' AS VARCHAR(50)) AS CROLENAME, ISNULL(B.NEDITDAYS,0) AS NEDITDAYS, ISNULL(B.NDELDAYS,0) AS NDELDAYS, 
			ADDEDIT=CASE WHEN ISNULL(B.PRODCODE,CAST('' as varbinary))=CAST('' as varbinary) THEN 'A' ELSE 'E' END
		FROM [USERROLES] A
			LEFT OUTER JOIN UDTBLUSERSETTINGS B ON A.PRODCODE=B.PRODCODE AND A.[USER_ROLES]=B.CUSRROLENM AND B.CUSERROLES='ROLE'
		WHERE A.[PRODCODE]=@PRODCODE
	UNION ALL
	SELECT DISTINCT A.PRODCODE AS PRODCODE, 'USER' AS  CUSERROLES, A.[USER] AS CUSRROLENM,
			A.[USER_ROLES] AS CROLENAME, CASE WHEN ISNULL(B.NEDITDAYS,0)=0 THEN ISNULL(C.NEDITDAYS,0) ELSE ISNULL(B.NEDITDAYS,0) END AS NEDITDAYS, 
			CASE WHEN ISNULL(B.NDELDAYS,0)=0 THEN ISNULL(C.NDELDAYS,0) ELSE ISNULL(B.NDELDAYS,0) END AS NDELDAYS,
			ADDEDIT=CASE WHEN ISNULL(B.PRODCODE,CAST('' as varbinary))=CAST('' as varbinary) THEN 'A' ELSE 'E' END
		FROM [USER] A
			LEFT OUTER JOIN UDTBLUSERSETTINGS B ON A.PRODCODE=B.PRODCODE AND A.[USER]=B.CUSRROLENM AND B.CUSERROLES='USER'
			LEFT OUTER JOIN UDTBLUSERSETTINGS C ON B.PRODCODE=C.PRODCODE AND B.[CUSRROLENM]=C.[CUSRROLENM] AND C.CUSERROLES='ROLE'
		WHERE A.[PRODCODE]=@PRODCODE
END

