CREATE TABLE GSTAPILICMAST
(
	GSTAPILICID INT IDENTITY(1,1),
	GSTAPPNAME VARCHAR(100),
	GSPUSERID VARCHAR(250),
	GSPPASSWD VARCHAR(250), 
	CREATEDON SMALLDATETIME,
	CREATEDBY VARCHAR(20)
)

